import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { trpc } from "@/utils/trpc";
import { ComputerCard } from "@/components/computer-card";
import { AddComputer } from "@/components/add-computer";
import { Header } from "@/components/header";

const Home: NextPage = () => {
  const computers = trpc.computersRouter.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Traffic Blocker | Computers</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid min-h-screen grid-rows-[4rem,1fr] bg-slate-200 font-sans">
        <Header action={<AddComputer refetch={computers.refetch} />} />
        <div className="flex flex-row flex-wrap content-start gap-4 p-8">
          {computers.isLoading && <p>Loading...</p>}
          {computers.data?.map((computer) => (
            <ComputerCard
              key={computer.macAddress}
              computer={computer}
              refetch={computers.refetch}
            />
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
